name: Robot Scraper LunaTec

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ejecutar-robot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install httpx beautifulsoup4

      - name: Ejecutar Scraper
        env:
          RENDER_EXTERNAL_URL: 'https://scraping-tus.onrender.com'
        run: python scraper.py
